# Generated by Django 4.2.10 on 2026-05-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office_or_field',
            field=models.CharField(choices=[('Office', 'Main Office HQ'), ('Field', 'On-Site / Field Projects')], default='Office', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Site Engineer', 'Site Engineer'), ('Safety Officer', 'Safety Officer'), ('Foreman', 'Foreman'), ('Estimator', 'Quantity Surveyor / Estimator'), ('Architect', 'Project Architect'), ('HR Admin', 'HR & Administrative Staff'), ('Procurement', 'Logistics & Procurement')], default='Foreman', max_length=100),
        ),
    ]
