# Generated by Django 4.2.10 on 2026-05-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_assignmentlocation_employeerole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_on_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_duty_toggle',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
