# Generated by Django 4.2.10 on 2026-05-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_userprofile_is_on_duty_userprofile_last_duty_toggle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_duty_toggle',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_on_duty',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
