# Generated by Django 4.2.10 on 2026-05-20 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_remove_userprofile_last_duty_toggle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='crud.assignmentlocation'),
        ),
    ]
