# Generated by Django 4.2.10 on 2026-05-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_employeerole_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerole',
            name='assignment',
        ),
    ]
