# Generated by Django 4.2.10 on 2026-05-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_remove_employeerole_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlocation',
            name='icon',
            field=models.CharField(default='bi-geo-alt-fill', max_length=50),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='color',
            field=models.CharField(default='#3d7fff', max_length=20),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='icon',
            field=models.CharField(default='bi-briefcase-fill', max_length=50),
        ),
        migrations.AddField(
            model_name='gender',
            name='color',
            field=models.CharField(default='#c4b5fd', max_length=20),
        ),
        migrations.AddField(
            model_name='gender',
            name='icon',
            field=models.CharField(default='bi-gender-ambiguous', max_length=50),
        ),
    ]
