# Generated by Django 4.2.10 on 2026-05-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_department_userprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
