# Generated by Django 4.2.10 on 2026-05-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_remove_userprofile_department_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
