# Generated by Django 4.2.10 on 2026-10-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_adminotp_adminregistrationrequest_adminface'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminotp',
            name='purpose',
            field=models.CharField(default='register', max_length=10),
        ),
        migrations.AddField(
            model_name='adminregistrationrequest',
            name='face_photo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
